front_blog/ddf/urls.py
from django.urls import path

from ddf import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('share/', views.share, name='share'),
    path('list/', views.list, name='list'),
    path('about/', views.about, name='about'),
    path('gbook/', views.gbook, name='gbook'),
    path('info/', views.info, name='info'),
    path('infopic/', views.infopic, name='infopic'),

    path('', views.index)
]

front_blog/front_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from ddf import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ddf/', include(('ddf.urls', 'ddf'), namespace='ddf')),

    path('', views.index)
]

front_blog/ddf/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=10, verbose_name='栏目名称', null=False, unique=True)
    alias = models.CharField(max_length=10, verbose_name='栏目别名', null=False, unique=True)
    keywords = models.CharField(max_length=10, null=True, verbose_name='关键字')
    describe = models.CharField(max_length=255, null=True, verbose_name='描述')

    class Meta:
        db_table = 'category'


class Article(models.Model):
    title = models.CharField(max_length=10, verbose_name='标题', null=False, unique=True)
    content = models.TextField()
    keywords = models.CharField(max_length=10, null=True, verbose_name='关键字')
    describe = models.CharField(max_length=255, null=True, verbose_name='描述')
    category = models.ForeignKey(Category, verbose_name='栏目', on_delete=models.CASCADE)
    tags = models.CharField(max_length=998, null=True, verbose_name='标签')
    visibility = models.BooleanField(default=0)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='时间', null=True)

    class Meta:
        db_table = 'article'




front_blog/ddf/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render

from ddf.models import Article, Category


def index(request):
    articles = Article.objects.all()
    categories = Category.objects.all()
    counts = Article.objects.values('category_id').annotate(Count('id'))
    # 分页
    page = int(request.GET.get('page', 1))
    pg = Paginator(articles, 5)
    ddf = pg.page(page)
    return render(request, 'index.html', {'articles': articles,
                                          'categories': categories,
                                          'counts': counts,
                                          'ddf': ddf})


def share(request):
    articles = Article.objects.all()
    # 分页
    page = int(request.GET.get('page', 1))
    pg = Paginator(articles, 2)
    ddf = pg.page(page)
    return render(request, 'share.html', {'articles': articles, 'ddf': ddf})


def list(request):
    articles = Article.objects.all()
    categories = Category.objects.all()
    counts = Article.objects.values('category_id').annotate(Count('id'))
    # 分页
    page = int(request.GET.get('page', 1))
    pg = Paginator(articles, 5)
    ddf = pg.page(page)
    return render(request, 'list.html', {'articles': articles, 'ddf': ddf, 'categories': categories, 'counts': counts})


def about(request):
    categories = Category.objects.all()
    counts = Article.objects.values('category_id').annotate(Count('id'))
    return render(request, 'about.html', {'categories': categories, 'counts': counts})


def gbook(request):
    categories = Category.objects.all()
    counts = Article.objects.values('category_id').annotate(Count('id'))
    return render(request, 'gbook.html', {'categories': categories, 'counts': counts})


def info(request):
    articles = Article.objects.all()
    categories = Category.objects.all()
    counts = Article.objects.values('category_id').annotate(Count('id'))
    return render(request, 'info.html', {'articles': articles, 'categories': categories, 'counts': counts})


def infopic(request):
    categories = Category.objects.all()
    counts = Article.objects.values('category_id').annotate(Count('id'))
    return render(request, 'infopic.html', {'categories': categories, 'counts': counts})

front_blog/templates/about.html

{% extends 'base_main.html' %}

{% block head %}
    {{ block.super}}
{% endblock %}

{% block css %}
    {{ block.super}}
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/js/hc-sticky.js"></script>
    <script type="text/javascript" src="/static/js/comm.js"></script>
    <script src="/static/js/modernizr.js"></script>
{% endblock %}

{% block content1 %}
    {{ block.super}}
{% endblock %}

{% block content %}
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/images/4.jpg"></i>
          <p><b>DDF</b>，一个凡人修仙！08年踏入修仙之路。一直潜心研究修仙技术，修仙之路没有尽头。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="/static/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for category in categories %}
                <li>
                    <a href="/">
                    {{ category.name }}
                        {% for count in counts %}
                            {% if category.id == count.category_id %}
                            ({{ count.id__count }})
                            {% endif %}
                        {% endfor %}
                    </a>
                </li>
            {% endfor %}
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/images/wx1.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
     <div class="about">
         <p>tset1<br />
             <br />
             test2<br />
            <br />
             <img src="/static/images/1.jpg">
             tset3<br />
             <br />
             tset4<br />
             <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，110(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 120（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！</p>
            <br />
            <h2>About my blog</h2>
          &nbsp;<p>域 名：暂无 创建于xxxx年xx月xx日&nbsp;</p>
            <br />
            <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
            <br />
            <p>备案号：蜀ICP备11002373号-1</p>
            <br />
            <p>程 序：PYTHON </p>

     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="https://ddf118.github.io/" target="_blank">DDF个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

front_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    {% endblock %}
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
    {% block content1 %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>
</html>

front_blog/templates/base_main.html

{% extends 'base.html' %}

{% block head %}
    <meta charset="UTF-8">
    <title>DDF个人博客</title>
    <meta name="keywords" content="个人博客,DDF个人博客" />
    <meta name="description" content="DDF个人博客" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}

{% block css %}
    <link href="/static/css/base.css" rel="stylesheet">
    <link href="/static/css/index.css" rel="stylesheet">
    <link href="/static/css/m.css" rel="stylesheet">
{% endblock %}
{% block content1 %}
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="{% url 'ddf:index' %}">DDF个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'ddf:index' %}">网站首页</a></li>
      <li><a href="{% url 'ddf:share' %}">我的相册</a></li>
      <li><a href="{% url 'ddf:list' %}">我的日记</a></li>
      <li><a href="{% url 'ddf:about' %}">关于我</a></li>
      <li><a href="{% url 'ddf:gbook' %}">留言</a></li>
      <li><a href="{% url 'ddf:info' %}">内容页</a></li>
      <li><a href="{% url 'ddf:infopic' %}">内容页</a></li>
    </ul>
</nav>
</header>
{% endblock %}


front_blog/templates/gbook.html

{% extends 'base_main.html' %}

{% block head %}
    {{ block.super}}
{% endblock %}

{% block css %}
    {{ block.super}}
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/js/hc-sticky.js"></script>
    <script type="text/javascript" src="/static/js/comm.js"></script>
    <script src="/static/js/modernizr.js"></script>
{% endblock %}

{% block content1 %}
    {{ block.super}}
{% endblock %}

{% block content %}
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/images/4.jpg"></i>
          <p><b>DDF</b>，一个凡人修仙！08年踏入修仙之路。一直潜心研究修仙技术，修仙之路没有尽头。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="/static/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for category in categories %}
                <li>
                    <a href="/">
                    {{ category.name }}
                        {% for count in counts %}
                            {% if category.id == count.category_id %}
                            ({{ count.id__count }})
                            {% endif %}
                        {% endfor %}
                    </a>
                </li>
            {% endfor %}
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/images/wx1.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
<div class="gbook">
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-21 </span> 夜月归途</p>
          <p class="fbinfo">从朋友圈分享的文章《我为什么要做个人网站》过来的，自习看了下你的网站非常不错，看的出来你一直在坚持!</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>感谢捧场啊！看了你的网站，有两个月没更新了哦~</p>
        </ul>
      </div>
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-10 </span> 周宏</p>
          <p class="fbinfo">读《从今日起，我永久卸载今日头条》有感。正如作者所说，这个APP抓住了很多人性的特点，在简单、重复、爽这三点上做到了极致。但是我认为永久卸载这个想法比较荒诞，任何东西你只要有自控力，就能将它为我所用。曾经一度我也是刷头条根本停不下来</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>嗯，我也是自制力有限，删除头条就是矫枉过正而已，这个因人而异，不强求他人，也不想标题党。</p>
        </ul>
      </div>
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-09 </span> 文颖</p>
          <p class="fbinfo">加油吖</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>感谢第一条留言的支持！：）</p>
        </ul>
      </div>
      <div class="gbox">
        <form action="../../enews/index.php" method="post" name="form1" id="form1">
          <p> <strong>来说点儿什么吧...</strong></p>
          <p><span> 您的姓名:</span>
            <input name="name" type="text" id="name">
            *</p>
          <p><span>联系邮箱:</span>
            <input name="email" type="text" id="email">
            *</p>
          <p><span class="tnr">留言内容:</span>
            <textarea name="lytext" cols="60" rows="12" id="lytext"></textarea>
          </p>
          <p>
            <input type="submit" name="Submit3" value="提交">
            <input name="enews" type="hidden" id="enews" value="AddGbook">
          </p>
        </form>
      </div>
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="https://ddf118.github.io/" target="_blank">DDF个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

front_blog/templates/index.html

{% extends 'base_main.html' %}

{% block head %}
    {{ block.super}}
{% endblock %}
{% block css %}
    {{ block.super}}
{% endblock %}
{% block js %}
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/comm.js"></script>
    <script src="/static/js/modernizr.js"></script>
{% endblock %}
{% block content1 %}
    {{ block.super}}
{% endblock %}
{% block content %}
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/images/4.jpg"></i>
          <p><b>DDF</b>，一个凡人修仙！08年踏入修仙之路。一直潜心研究修仙技术，修仙之路没有尽头。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="/static/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for category in categories %}
                <li>
                    <a href="/">
                    {{ category.name }}
                        {% for count in counts %}
                            {% if category.id == count.category_id %}
                            ({{ count.id__count }})
                            {% endif %}
                        {% endfor %}
                    </a>
                </li>
            {% endfor %}
        </ul>
      </div>
      <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
            {% for article in articles%}
                <li><a href="/">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="https://ddf118.github.io/">DDF个人博客</a> <a href="https://ddf118.github.io/">DDF博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/images/wx1.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
      {% for article in ddf%}
      <li><i><a href="/"><img src="/static/images/{{ forloop.counter }}.jpg"></a></i>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.describe }}</p>
      </li>
      {% endfor %}
      <li>
        {% if ddf.has_previous %}
        <a href="{% url 'ddf:index' %}?page={{ ddf.previous_page_number }}" ><span>&laquo;上一页</span> </a>
        {% endif %}
        {% for i in ddf.paginator.page_range %}
        <a href="{% url 'ddf:index' %}?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if ddf.has_next %}
        <a href="{% url 'ddf:index' %}?page={{ ddf.next_page_number }}" ><span>&raquo;下一页</span> </a>
        {% endif %}
      </li>
  </main>

</article>
<footer>
  <p>Design by <a href="https://ddf118.github.io/" target="_blank">DDF个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

front_blog/templates/list.html

{% extends 'base_main.html' %}

{% block head %}
    {{ block.super}}
{% endblock %}
{% block css %}
    {{ block.super}}
{% endblock %}
{% block js %}
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/js/hc-sticky.js"></script>
    <script type="text/javascript" src="/static/js/comm.js"></script>
    <script src="/static/js/modernizr.js"></script>
{% endblock %}
{% block content1 %}
    {{ block.super}}
{% endblock %}
{% block content %}
<article>
  <aside class="l_box">
        <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
        </div>
        <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for category in categories %}
                <li>
                    <a href="/">
                    {{ category.name }}
                        {% for count in counts %}
                            {% if category.id == count.category_id %}
                            ({{ count.id__count }})
                            {% endif %}
                        {% endfor %}
                    </a>
                </li>
            {% endfor %}
        </ul>
      </div>
        <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
            {% for article in articles%}
                <li><a href="/">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
      </div>
        <div class="tuijian">
        <h2>点击排行</h2>
        <ul>
            {% for article in articles%}
                <li><a href="/">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
        </div>
        <div class="cloud">
      <h2>标签云</h2>
      <ul>
        <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
      </ul>
    </div>
        <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/images/wx1.jpg">
      </ul>
    </div>
  </aside>
    <main class="r_box">
      {% for article in ddf%}
      <li><i><a href="/"><img src="/static/images/{{ forloop.counter }}.jpg"></a></i>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.describe }}</p>
      </li>
      {% endfor %}
      <li>
        {% if ddf.has_previous %}
        <a href="{% url 'ddf:list' %}?page={{ ddf.previous_page_number }}" ><span>&laquo;上一页</span> </a>
        {% endif %}
        {% for i in ddf.paginator.page_range %}
        <a href="{% url 'ddf:list' %}?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if ddf.has_next %}
        <a href="{% url 'ddf:list' %}?page={{ ddf.next_page_number }}" ><span>&raquo;下一页</span> </a>
        {% endif %}
      </li>
  </main>
</article>
<footer>
  <p>Design by <a href="https://ddf118.github.io/" target="_blank">DDF个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

front_blog/templates/share.html

{% extends 'base_main.html' %}

{% block head %}
    {{ block.super}}
{% endblock %}
{% block css %}
    {{ block.super}}
{% endblock %}
{% block js %}
    <script src="/static/js/modernizr.js"></script>
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/js/comm.js"></script>
    <script src="/static/js/scrollReveal.js"></script>
{% endblock %}
{% block content1 %}
    {{ block.super}}
{% endblock %}
{% block content %}
<article>
  <div class="picbox">
      <ul>
          {% for article in ddf%}
      <li data-scroll-reveal="enter bottom over 1s" ><a href="/"><i><img src="/static/images/{{ forloop.counter }}.jpg"></i>
        <div class="picinfo">
          <h3>{{ article.title }}</h3>
          <span>{{ article.describe }}</span> </div>
        </a></li>
          {% endfor %}
    </ul>
  </div>
  <div class="pagelist">
      {% if ddf.has_previous %}
      <a class="allpage" href="{% url 'ddf:share' %}?page={{ ddf.previous_page_number }}"><b><span>&laquo;上一页</span></b></a>
      {% endif %}
      {% for i in ddf.paginator.page_range %}
      <a href="{% url 'ddf:share' %}?page={{ i }}"  class="curPage">{{ i }}</a>
      {% endfor %}&nbsp;&nbsp;
      {% if ddf.has_next %}
      <a href="{% url 'ddf:share' %}?page={{ ddf.next_page_number }}" ><span>&raquo;下一页</span></a>
      {% endif %}
  </div>
</article>
<footer>
  <p>Design by <a href="https://ddf118.github.io/" target="_blank">DDF个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}