blog/article/urls.py

from django.urls import path

from article import views

urlpatterns = [
    # 文章首页
    path('article/', views.article, name='article'),
    # 增加文章
    path('add_article/', views.add_article, name='add_article'),
    # 编辑文章
    path('edit_article/<int:id>/', views.edit_article, name='edit_article'),
    # 删除文章
    path('del_article/<int:id>/', views.del_article, name='del_article'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static

from blog import settings
from utils.upload_image import upload_image
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('category/', include(('category.urls', 'category'), namespace='category')),
    # kindeditor编辑器上传图片地址
    re_path(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    # 首页路径
    path('', views.login),
]

# 配置media访问路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/category/urls.py

from django.urls import path

from category import views

urlpatterns = [
    # 栏目首页
    path('category/', views.category, name='category'),
    # # 增加栏目
    path('add_category/', views.add_category, name='add_category'),
    # # 编辑栏目
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    # # 删除栏目
    path('del_category/<int:id>/', views.del_category, name='del_category'),
]

blog/user/urls.py

from django.urls import path

from user import views

urlpatterns = [
    # 注册
    path('register/', views.register, name='register'),
    # 登录
    path('login/', views.login, name='login'),
    # 报告首页
    path('index/', views.index, name='index'),
    # # 注销
    path('logout/', views.logout, name='logout'),
]

blog/article/models.py
from django.db import models

from category.models import Category


class Article(models.Model):
    title = models.CharField(max_length=10, verbose_name='标题', null=False, unique=True)
    content = models.TextField()
    keywords = models.CharField(max_length=10, null=True, verbose_name='关键字')
    describe = models.CharField(max_length=255, null=True, verbose_name='描述')
    category = models.ForeignKey(Category, verbose_name='栏目', on_delete=models.CASCADE)
    tags = models.CharField(max_length=998, null=True, verbose_name='标签')
    visibility = models.BooleanField(default=0)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='时间', null=True)

    class Meta:
        db_table = 'article'

blog/category/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=10, verbose_name='栏目名称', null=False, unique=True)
    alias = models.CharField(max_length=10, verbose_name='栏目别名', null=False, unique=True)
    keywords = models.CharField(max_length=10, null=True, verbose_name='关键字')
    describe = models.CharField(max_length=255, null=True, verbose_name='描述')

    class Meta:
        db_table = 'category'

blog/article/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from article.models import Article
from category.models import Category


def article(request):
    """
    文章展示方法
    """
    if request.method == 'GET':
        # 获取所有的文章
        articles = Article.objects.all()
        page = int(request.GET.get('page', 1))
        pg = Paginator(articles, 2)
        ddf = pg.page(page)
        return render(request, 'article.html',
                      {'articles': articles, 'ddf': ddf})


def add_article(request):
    """
    文章增加方法
    """
    if request.method == 'GET':
        categories = Category.objects.all()
        articles = Article.objects.all()
        return render(request, 'add.html', {'categories': categories, 'articles': articles})
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        keywords = request.POST.get('keywords')
        describe = request.POST.get('describe')
        category_id = request.POST.get('category')
        tags = request.POST.get('tags')
        visibility = request.POST.get('visibility')
        # 使用all()方法进行判断，如果文章标题和内容任何一个参数没有填写，则返回错误信息
        if not all([title, content]):
            msg = '请填写完整的参数'
            return render(request, 'add.html', {'msg': msg})
        # 添加到数据库文章
        Article.objects.create(title=title,
                               content=content,
                               keywords=keywords,
                               describe=describe,
                               category_id=category_id,
                               tags=tags,
                               visibility=visibility)
        # 创建文章成功后，跳转到文章列表页面
        return HttpResponseRedirect(reverse('article:article'))


def edit_article(request, id):
    """
    文章编辑方法
    """
    if request.method == 'GET':
        article = Article.objects.filter(pk=id).first()
        categories = Category.objects.all()
        return render(request, 'edit.html', {'ddf': article, 'categories': categories})
    if request.method == 'POST':
        # 获取文章的标题和内容
        title = request.POST.get('title')
        content = request.POST.get('content')
        keywords = request.POST.get('keywords')
        describe = request.POST.get('describe')
        category_id = request.POST.get('category')
        tags = request.POST.get('tags')
        visibility = request.POST.get('visibility')
        # 使用all()方法进行判断，如果文章标题和内容任何一个参数没有填写，则返回错误信息
        if not all([title, content]):
            msg = '请填写完整的参数'
            return render(request, 'edit.html', {'msg': msg})
        # 编辑文章
        Article.objects.filter(pk=id).update(title=title,
                                             content=content,
                                             keywords=keywords,
                                             describe=describe,
                                             category_id=category_id,
                                             tags=tags,
                                             visibility=visibility)
        # 修改文章成功后，跳转到文章列表页面
        return HttpResponseRedirect(reverse('article:article'))


def del_article(request, id):
    if request.method == 'GET':
        Article.objects.filter(pk=id).delete()
        return HttpResponseRedirect(reverse('article:article'))

blog/category/views.py
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from article.models import Article
from category.models import Category


def category(request):
    """
    栏目展示方法
    """
    if request.method == 'GET':
        # 获取所有的栏目
        categories = Category.objects.all()
        counts = Article.objects.values('category_id').annotate(Count('id'))
        return render(request, 'category.html', {'categories': categories,
                                                 'counts': counts,})


def add_category(request):
    """
    栏目增加方法
    """
    # if request.method == 'GET':
    #     return render(request, 'add-category.html')
    if request.method == 'POST':
        name = request.POST.get('name')
        alias = request.POST.get('alias')
        keywords = request.POST.get('keywords')
        describe = request.POST.get('describe')
        # 使用all()方法进行判断，如果文章标题和内容任何一个参数没有填写，则返回错误信息
        if not all([name, alias]):
            msg = '请填写完整的参数'
            return render(request, 'add-category.html', {'msg': msg})
        # 添加到数据库栏目
        Category.objects.create(name=name,
                                alias=alias,
                                keywords=keywords,
                                describe=describe)
        # 创建文章成功后，跳转到栏目列表页面
        return HttpResponseRedirect(reverse('category:category'))


def edit_category(request, id):
    """
    栏目编辑方法
    """
    if request.method == 'GET':
        category = Category.objects.filter(pk=id).first()
        return render(request, 'edit-category.html', {'category': category})
    if request.method == 'POST':
        # 获取栏目的标题和内容
        name = request.POST.get('name')
        alias = request.POST.get('alias')
        keywords = request.POST.get('keywords')
        describe = request.POST.get('describe')
        # 使用all()方法进行判断，如果栏目标题和内容任何一个参数没有填写，则返回错误信息
        if not all([name, alias]):
            msg = '请填写完整的参数'
            return render(request, 'edit-category.html', {'msg': msg})
        # 编辑栏目
        Category.objects.filter(pk=id).update(name=name,
                                              alias=alias,
                                              keywords=keywords,
                                              describe=describe)
        # 修改栏目成功后，跳转到栏目列表页面
        return HttpResponseRedirect(reverse('category:category'))


def del_category(request, id):
    if request.method == 'GET':
        Category.objects.filter(pk=id).delete()
        return HttpResponseRedirect(reverse('category:category'))

blog/templates/article.html

{% extends 'base_main.html' %}

{% block meta %}
  {{ block.super }}
{% endblock %}

{% block title %}
  <title>文章 - DDF博客管理系统</title>
{% endblock %}

{% block css %}
  {{ block.super }}
{% endblock %}

{% block js %}
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/static/js/respond.min.js" type="text/javascript"></script>
    <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
{% endblock %}

{% block content%}
<section class="container-fluid">
    <header>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                    <a class="navbar-brand" href="{% url 'user:index' %}">SAMSARA</a> </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="">消息 <span class="badge">1</span></a></li>
                        <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'user:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
                        <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
                    </ul>
                    <form action="" method="post" class="navbar-form navbar-right" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">搜索</button>
                            </span> </div>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'user:index' %}">报告</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li class="active"><a href="{% url 'article:article' %}">文章</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'category:category' %}">栏目</a></li>
            </ul>
        </aside>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
            <form action="" method="post" >
                <h1 class="page-header">操作</h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'article:add_article' %}">增加文章</a></li>
                </ol>
                <h1 class="page-header">管理 <span class="badge">{{ articles.count }}</span></h1>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                            <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                            <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">栏目</span></th>
                            <th class="hidden-sm"><span class="glyphicon glyphicon-tag"></span> <span class="visible-lg">标签</span></th>
                            <th class="hidden-sm"><span class="glyphicon glyphicon-comment"></span> <span class="visible-lg">关键字</span></th>
                            <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                            <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in ddf %}
                        <tr>
                            <td><input type="checkbox" class="input-control" name="checkbox[]" value="" /></td>
                            <td class="article-title">{{ i.title }}</td>
                            <td>{{ i.category.name }}</td>
                            <td class="hidden-sm">{{ i.tags }}</td>
                            <td class="hidden-sm">{{ i.keywords }}</td>
                            <td>{{ i.create_time }}</td>
                            <td><a href="{% url 'article:edit_article' i.id %}">修改</a> <a href="{% url 'article:del_article' i.id %}">删除</a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <footer class="message_footer">
                    <nav>
                        <div class="btn-toolbar operation" role="toolbar">
                            <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
                            <div class="btn-group" role="group">
                                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
                            </div>
                        </div>

                        <ul class="pagination pagenav">
                            {% if ddf.has_previous %}
                            <li><a href="{% url 'article:article' %}?page={{ ddf.previous_page_number }}" aria-label=""> <span aria-hidden="true">&laquo;</span> </a> </li>
                            {% endif %}
                            {% for i in ddf.paginator.page_range %}
                            <li><a href="{% url 'article:article' %}?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                            {% if ddf.has_next %}
                            <li><a href="{% url 'article:article' %}?page={{ ddf.next_page_number }}" aria-label=""> <span aria-hidden="true">&raquo;</span> </a> </li>
                            {% endif %}
                        </ul>

                    </nav>
                </footer>

            </form>
        </div>
    </div>
</section>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
<script>
//是否确认删除
$(function(){
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id
		if (event.srcElement.outerText == "删除")
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/Article/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});
});
</script>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% block meta %}
    {% endblock %}
    {% block title %}
    {% endblock %}
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body class="user-select">
    {% block content %}
    {% endblock %}
</body>
</html>

blog/templates/category.html

{% extends 'base_main.html' %}

{% block meta %}
  {{ block.super }}
{% endblock %}

{% block title %}
  <title>栏目 - DDF博客管理系统</title>
{% endblock %}

{% block css %}
  {{ block.super }}
{% endblock %}

{% block js %}
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/static/js/respond.min.js" type="text/javascript"></script>
    <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
{% endblock %}

{% block content%}
<section class="container-fluid">
  <header>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                    <a class="navbar-brand" href="{% url 'user:index' %}">SAMSARA</a> </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="">消息 <span class="badge">1</span></a></li>
                        <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'user:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
                        <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
                    </ul>
                    <form action="" method="post" class="navbar-form navbar-right" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">搜索</button>
                            </span> </div>
                    </form>
                </div>
            </div>
        </nav>
    </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'user:index' %}">报告</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'article:article' %}">文章</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li class="active"><a href="{% url 'category:category' %}">栏目</a></li>
            </ul>
        </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <div class="col-md-5">
          <h1 class="page-header">添加</h1>
          <form action="{% url 'category:add_category' %}" method="post" autocomplete="off">
              {% csrf_token %}
            <div class="form-group">
              <label for="category-name">栏目名称</label>
              <input type="text" id="category-name" name="name" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
              <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
            <div class="form-group">
              <label for="category-alias">栏目别名</label>
              <input type="text" id="category-alias" name="alias" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
              <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span> </div>
              {% comment %}
            <div class="form-group">
              <label for="category-fname">父节点</label>
              <select id="category-fname" class="form-control" name="fid">
                <option value="0" selected>无</option>
                <option value="1">前端技术</option>
                <option value="2">后端程序</option>
                <option value="3">管理系统</option>
                <option value="4">授人以渔</option>
                <option value="5">程序人生</option>
              </select>
              <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span> </div>
              {% endcomment %}
            <div class="form-group">
              <label for="category-keywords">关键字</label>
              <input type="text" id="category-keywords" name="keywords" class="form-control" placeholder="在此处输入栏目关键字" autocomplete="off">
              <span class="prompt-text">关键字会出现在网页的keywords属性中。</span> </div>
            <div class="form-group">
              <label for="category-describe">描述</label>
              <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off"></textarea>
              <span class="prompt-text">描述会出现在网页的description属性中。</span> </div>
            <button class="btn btn-primary" type="submit" name="submit">添加新栏目</button>
          </form>
        </div>
        <div class="col-md-7">
          <h1 class="page-header">管理 <span class="badge">{{ categories | length }}</span></h1>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-list-alt"></span> <span class="visible-lg">别名</span></th>
                  <th><span class="glyphicon glyphicon-pushpin"></span> <span class="visible-lg">总数</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>
              {% for category in categories %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ category.name }}</td>
                  <td>{{ category.alias }}</td>

                <td>
                    {% for count in counts %}
                        {% if category.id == count.category_id %}
                            {{ count.id__count }}
                        {% endif %}
                    {% endfor %}
                </td>

                  <td><a href="{% url 'category:edit_category' category.id %}">修改</a> <a href="{% url 'category:del_category' category.id %}">删除</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <span class="prompt-text"><strong>注：</strong>删除一个栏目也会删除栏目下的文章和子栏目,请谨慎删除!</span> </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
<script>
//是否确认删除
$(function(){   
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id  
		if (event.srcElement.outerText === "删除") 
		{
			if(window.confirm("此操作不可逆，再见！"))
			{
				$.ajax({
					type: "POST",
					url: "/Category/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面   
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});   
});
</script>
{% endblock %}

blog/templates/edit-category.html

{% extends 'base_main.html' %}

{% block meta %}
  {{ block.super }}
{% endblock %}

{% block title %}
  <title>修改栏目 - DDF博客管理系统</title>
{% endblock %}

{% block css %}
  {{ block.super }}
{% endblock %}

{% block js %}
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/static/js/respond.min.js" type="text/javascript"></script>
    <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
{% endblock %}

{% block content%}
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="{% url 'user:index' %}">SAMSARA</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'user:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
      <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'user:index' %}">报告</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="{% url 'article:article' %}">文章</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li class="active"><a href="{% url 'category:category' %}">栏目</a></li>
            </ul>
        </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <h1 class="page-header">修改栏目</h1>
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="category-name">栏目名称</label>
          <input type="text" id="category-name" name="name" value="{{ category.name }}" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
          <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
        <div class="form-group">
          <label for="category-alias">栏目别名</label>
          <input type="text" id="category-alias" name="alias" value="{{ category.alias }}" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
          <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span> </div>
            {% comment %}
          <div class="form-group">
          <label for="category-fname">父节点</label>
          <select id="category-fname" class="form-control" name="fid">
            <option value="0" selected>无</option>
            <option value="1">前端技术</option>
            <option value="2">后端程序</option>
            <option value="3">管理系统</option>
            <option value="4">授人以渔</option>
            <option value="5">程序人生</option>
          </select>
          <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span> </div>
            {% endcomment %}
        <div class="form-group">
          <label for="category-keywords">关键字</label>
          <input type="text" id="category-keywords" name="keywords" value="{{ category.keywords }}" class="form-control" placeholder="在此处输入栏目关键字" autocomplete="off">
          <span class="prompt-text">关键字会出现在网页的keywords属性中。</span> </div>
        <div class="form-group">
          <label for="category-describe">描述</label>
          <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off">{{ category.describe }}</textarea>
          <span class="prompt-text">描述会出现在网页的description属性中。</span> </div>
          <input type="submit" value="更新">
      </form>
    </div>
  </div>
</section>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/admin-scripts.js"></script>
{% endblock %}